### ISSUE TITLE
Sofatisch

### ISSUE THREAD

**Issue by romanblick** [romanlehnert/home#2]
Sofatisch soll aus Massivholz Eiche sein:
- Platte: 840mm x 750mm x 20mm
- Tischwinkel
- 4 Füße: 480mm x 50mm x 50mm
- Passende Tischzargen (müssen noch vermessen werden)

**Comment by romanlehnert** [comment]
http://www.ebay.de/itm/K57-Eichen-Tischbeine-Kantholz-abgerundet-Massiv-50-x-50-mm-Lange-42cm-/191910086321?hash=item2caebb86b1

**Comment by romanlehnert** [comment]
http://www.ebay.de/itm/K64-Eichen-Tischbeine-Kantholz-abgerundet-Massiv-40-x-40mm-Lange-40cm-/201614170322?hash=item2ef12418d2

**Comment by romanlehnert** [comment]
http://www.ebay.de/itm/K57-Eichen-Tischbeine-Kantholz-abgerundet-Massiv-50-x-50-mm-Lange-42cm-/191910086321?hash=item2caebb86b1

**Comment by romanlehnert** [comment]
http://www.ebay.de/itm/K61-Eichen-Tischbeine-Leimholz-Kantholz-abgerundet-Massiv-60-x60-mm-Lange-50cm-/201614148832?hash=item2ef123c4e0

**Comment by romanlehnert** [comment]
http://www.ebay.de/itm/K72-Eichen-Tischbeine-Leimholz-Kantholz-abgerundet-Massiv-80-x80-mm-Lange-50cm-/201640344479?hash=item2ef2b37b9f

**Comment by romanlehnert** [comment]
http://www.ebay.de/itm/K21-Eichen-Tischbeine-Kantholz-abgerundet-Leimholz-Massiv-60-x-60-mm-Lange-40cm-/201644392438?hash=item2ef2f13ff6

**Comment by romanlehnert** [comment]
http://www.ebay.de/itm/K64-Eichen-Tischbeine-Kantholz-abgerundet-Massiv-74-x74-mm-Lange-50cm-/191769845757?hash=item2ca65f9ffd

**Comment by romanlehnert** [comment]
Alternativ: 76 x 67cm
